### ISSUE TITLE
Avoid the use of implicitly unwrap optional

### ISSUE THREAD

**Issue by onmyway133** [fespinoza/linked-ideas-osx#17]
Hi, I just run the app. All went fine.

But when I click onto some buttons like "Left", "Right", ... it crashes

> fatal error: unexpectedly found nil while unwrapping an Optional value

There are some use of implicitly unwrap optional, like https://github.com/fespinoza/linked-ideas-osx/blob/master/LinkedIdeas/AligmentFunctions.swift#L59

that I think we can improve upon

Cheer 😁

**Comment by fespinoza** [comment]
thanks, i will take a look :)

**Comment by fespinoza** [comment]
i removed all the force unwrapping on #31

**Comment by onmyway133** [comment]
👍
